TodoApp/urls.py
from django.urls import path
from .views  import *


app_name="TodoApp"
urlpatterns = [
    path("create/", TaskCreateView.as_view(), name='task-create'),
    path('', TaskListView.as_view(), name='task-list'),
    path('<int:pk>/', TaskDetailViews.as_view(), name='task-details'),
    path('update/<int:pk>/', TaskUpdateViews.as_view(), name='task-update'),
    path('delete/<int:pk>/', TaskDeleteViews.as_view(), name='task-delete')
]

program/urls.py
from django.conf import settings
from django.conf.urls.static import static


"""
program URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""


from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('uploads.urls')),
    path('task/', include("TodoApp.urls"))
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# or you can used

TodoApp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=300, unique=True)
    description = models.TextField(max_length=520, blank=True, null=True)
    is_done = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("TodoApp:task-details", args=[self.id])

    def __str__(self):
        return f'Task #{self.id}'

uploads/models.py
import email
from email.mime import image
from pydoc import describe
from statistics import mode
from django.db import models

# Create your models here.
class Category(models.Model):
    title=models.CharField(max_length=90)
    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering=['-title']
        verbose_name_plural = 'Catrgories'



class Profile(models.Model):
    tech_stack = models.ForeignKey(Category, on_delete=models.CASCADE, unique=False)
    name = models.CharField(max_length=100, help_text='Enter your name')
    email = models.EmailField()
    image= models.FileField(upload_to = 'Files/')

    def __str__(self) -> str:
        return self.name
        
    def __repr__(self) -> str:
        return f' profile {self.name}, {self.image}'


class Book(models.Model):
    title = models.CharField(max_length=120)
    image = models.FileField(upload_to="files/")
    description = models.TextField(default="")
    price = models.IntegerField()
    discount = models.IntegerField()
    isbn = models.CharField(max_length=120, unique=True)
    is_published = models.BooleanField(default=True)
    rating = models.IntegerField()

    def __str__(self):
        return self.title




class UserInfoModels(models.Model):
    first_name = models.CharField(max_length=140)
    Last_name = models.CharField(max_length=140)
    email = models.EmailField()
    image = models.ImageField(upload_to='forms')

    def __str__(self) :
        return f'{self.first_name}'

TodoApp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields ="__all__"



class ConfirmForm(forms.Form):
    confirm = forms.BooleanField(label='is form completed')

uploads/forms.py
from dataclasses import fields
from inspect import Attribute
from .models import *
from django.forms import ModelForm, Form
from django import forms

class TeamForm(ModelForm):
    
    
    class Meta:
        model = Profile
        fields = '__all__'
# here you used the models as the medium to create the user form since there is already an info about the demands for the form to be created with.
# it always best to used and also fast to work with as you dont need to code for the information you demand from the user.
class BookCreateForm(ModelForm):

    class Meta:
        model = Book
        fields = "__all__"
        # exclude = ['first_name'] this is used to remove some of the Attribute out of the models or what the user have to be required to input

class ConfirmForm(forms.Form):
    confirm = forms.BooleanField(label="confirm delete")


# This class is used to create a form in which you code for the form.
class UserInfoForm(forms.Form):
    first_name = forms.CharField(max_length=140)
    Last_name = forms.CharField(max_length=140)
    email = forms.EmailField()
    image = forms.ImageField()


#below form is for user signup page 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User 
"""instead of creating another models for the user, we used the already created django user models and made some modifications to it"""

class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(SignupForm, self). __init__(*args, **kwargs)
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['username'].widget.attrs['placeholder'] = 'Enter Username '
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Last Name'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Password confirm'

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2") 
        """those are the fields we intent to used in the creation of the user page."""


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.fields['password'].widget.attrs['placeholder']= 'password'
        self.fields['username'].widget.attrs['placeholder']= 'Username'

TodoApp/views.py
#this part of the views explains only the generic views of django which is more useful if u dont have enough time to complete or to work with main views
from django.shortcuts import render
from .models import *
from .forms import *
from django.views.generic import CreateView #this is the view to be used while working on it first
from django.views.generic.list import ListView
from django.urls import reverse, reverse_lazy
# Create your views here.
# today we want to talk about generic views and how it can be used.
#if u inherit a function based view you still need to used function to declare it.


class TaskCreateView(CreateView):
    form_class = TaskForm #this is the form class we create for the task creation
    template_name = 'TodoApp/task_create.html' #here you call the template u want to used while creating the page for the project
    success_url = reverse_lazy("TodoApp:task-list")


class TaskListView(ListView): #look up for where the listview comes from before coding further
    #a generic views for ListViews, you need quaryset, tempalte name and context_object_name which wil be what you call at the template.
    queryset = Task.objects.all()
    template_name = 'TodoApp/task_list.html'
    context_object_name = 'tasks'

#to show the details of the task you created, you import detailsview from django genetic details.
from django.views.generic.detail import DetailView
# then declare or call it class
class TaskDetailViews(DetailView):
    model = Task
    template_name = 'TodoApp/task_list.html'

# for an update views, you need to import for edit in generic
from django.views.generic.edit import UpdateView, DeleteView

class TaskUpdateViews(UpdateView):
    model = Task
    template_name = 'TodoApp/task_update.html'
    fields = "__all__"
    success_url = reverse_lazy("TodoApp:task-list")

# in line 32, deleteview was already imported
class TaskDeleteViews(DeleteView):
    model = Task
    template_name = 'TodoApp/task_confirm_delete.html'
    success_url = reverse_lazy("TodoApp:task-list")

TodoApp/templates/TodoApp/task_confirm_delete.html
{% extends 'ImageApp/index.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/task_update.css' %}">
{% endblock %}

{% block content %}
        <div class="form-wrapper">
            
            <form class="team-form" method="POST" action="" enctype="multipart/form-data">
                <h2>delete Task: {{task.name}}</h2>
                {% csrf_token %}
                {{task.description}}
                {{form.as_p}}
                <button class="submit" type="delete"> Delete</button>
            </form>
        </div>
{% endblock %}

TodoApp/templates/TodoApp/task_create.html
{% extends 'ImageApp/index.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/task_update.css' %}">
{% endblock %}

{% block content %}
        <div class="form-wrapper">
            
            <form class="team-form" method="POST" action="" enctype="multipart/form-data">
                <h2>Create Task</h2>
                {% csrf_token %}
                {{form.as_p}}
                <button class="submit" type="submit"> Submit</button>
            </form>
        </div>
{% endblock %}

TodoApp/templates/TodoApp/task_detail.html
{% extends 'ImageApp/index.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/tasklist.css' %}">
{% endblock %}

{% block content %}
<div class="table-wrapper">
    <table border="1"> 
        <tr class="headings">
            <th>Task Id</th>
            <th>task Name</th>
            <th>Task Description</th>
            <th>Task Status</th>
        </tr>
        <tr>
            <td id="task-id">{{task.id}}</td>
            <td>{{task.name}}</td>
            <td>{{task.description}} lore</td>
            <td class="status">
                <a class="edit" href="{% url 'TodoApp:task-update' task.id %}">Edit</a>
                <a class="delete" href="{% url 'TodoApp:task-delete' task.id %}">Delete</a>
            </td>
        </tr>
       
        
    </table>
</div>
    
{% endblock %}

TodoApp/templates/TodoApp/task_list.html
{% extends 'ImageApp/index.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/tasklist.css' %}">
{% endblock %}

{% block content %}
<div class="table-wrapper">
    
    <table border="1"> 
        <tr class="headings">
            <th>Task Id</th>
            <th>task Name</th>
            <th>Task Description</th>
            <th>Task Status</th>
        </tr> 
        {% for item in tasks %}
        <tr>
            <td id="task-id">{{item.id}}</td>
            <td>{{item.name}}</td>
            <td>{{item.description}}</td>
            <td class="status">
                <a class="edit" href="{% url 'TodoApp:task-update' item.id %}">Edit</a>
                <a class="delete" href="{% url 'TodoApp:task-delete' item.id %}">Delete</a>
            </td>
        </tr>
        {% endfor %}
        
    </table>
</div>
    
{% endblock %}

TodoApp/templates/TodoApp/task_update.html
{% extends 'ImageApp/index.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/task_update.css' %}">
{% endblock %}

{% block content %}
        <div class="form-wrapper">
            
            <form class="team-form" method="POST" action="" enctype="multipart/form-data">
                <h2>Update Form</h2>
                {% csrf_token %}
                {{form.as_p}}
                <button class="submit" type="submit"> Submit</button>
                {%comment%}
                The views used here is all generic views for the sake of time not being on my side to do the 
                things that was expected of it to be done.
                {% endcomment%}
            </form>
        </div>
{% endblock %}